version: '3.4'

services:
  pdf_converter:
    image: docker.io/thecodingmachine/gotenberg:7
    container_name: pdf_conv
    ports:
      - 3001:3000
    networks:
      - documents_web
    restart: always

  thumbnail_service:
    image: docker.io/thecodingmachine/gotenberg:7
    container_name: pdf_conv
    ports:
      - 3001:3000
    networks:
      - documents_web
    restart: always

  cryoland.infrastructure.documents.web:
    image: ${DOCKER_REGISTRY-}cryolandinfrastructuredocumentsweb
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - documents_web
    depends_on:
      - pdf_converter
      - thumbnail_service
    restart: always

networks:
  documents_web:
    driver: bridge
